title: Awesomer title
author: GitHub User: Pecha
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here are some words that will trip search engines and tell 
  people what's up if they look through the xml.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
